### ISSUE TITLE
File icons + name disappear for current tab

### ISSUE THREAD

**Issue by straversi** [thomaslindstrom/no-caffeine-syntax#13]
no-caffeine-syntax with one-dark ui theme causes file icons and name to disappear on the active tab. Also cause other problems like off-centering for Set ui theme.

**Comment by straversi** [comment]
culprit: `background: @color-charcoal` under `// Fix One Dark tab colors` in base.less

**Comment by albertorestifo** [comment]
:+1:  OneDark theme

![image](https://cloud.githubusercontent.com/assets/1037048/9217695/2408250c-40cb-11e5-9403-8c77ee508354.png)

**Comment by albertorestifo** [comment]
Adding the following to my`style.less` file fixed it:

```
.tab-bar .tab div {
  z-index: 10;
}
```

Result:
![image](https://cloud.githubusercontent.com/assets/1037048/9217815/926a4bb4-40cc-11e5-85dc-d346eaa72579.png)

**Comment by thomaslindstrom** [comment]
I removed the hack that artificially tried to solve the problem with the `.tab-bar` background, fixing the issue where icons provided by `file-icons` would disappear. The fix is in `no-caffeine-syntax` `0.16.1`.

Off-centered icons is a problem with either `Seti UI` or `file-icons`. `Seti UI` has its own, built in, file icons.
